"""Add user_id to videos

Revision ID: 0553b1475b32
Revises: 3dc445722cb7
Create Date: 2025-10-17 10:10:15.755766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0553b1475b32'
down_revision: Union[str, Sequence[str], None] = '3dc445722cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###
