"""add column in invoice

Revision ID: 19d023d67ab4
Revises: 238919d78bc8
Create Date: 2025-09-30 13:19:53.495497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d023d67ab4'
down_revision: Union[str, Sequence[str], None] = '238919d78bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'is_paid')
    # ### end Alembic commands ###
