"""initial migration

Revision ID: c6c704beaf1a
Revises: 
Create Date: 2025-09-11 02:00:25.044540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c704beaf1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('parent_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'orders', ['parent_order_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('uploaded_images', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('uploaded_images', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('uploaded_images', 'prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_images', 'video_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_images', 'video_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_uploaded_images_filename'), table_name='uploaded_images')
    op.drop_column('uploaded_images', 'package')
    op.drop_column('uploaded_images', 'add_ons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_images', sa.Column('add_ons', sa.TEXT(), nullable=True))
    op.add_column('uploaded_images', sa.Column('package', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_uploaded_images_filename'), 'uploaded_images', ['filename'], unique=False)
    op.alter_column('uploaded_images', 'video_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_images', 'video_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_images', 'prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_images', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('uploaded_images', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'parent_order_id')
    # ### end Alembic commands ###
